In [7]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [9]:
from pathlib import Path
import pandas as pd
import re

CARPETA = Path("/content/drive/MyDrive/9. Gabs datos finales")
archivos = sorted(CARPETA.glob("*.xlsx"))

dfs = {} # Initialize the dictionary to store DataFrames

if not archivos:
    print(f"⚠️ No se encontraron archivos .xlsx en la carpeta: {CARPETA}")
    print("Por favor, verifica que la ruta sea correcta y que contenga archivos Excel.")
else:
    for archivo in archivos:
        nombre = archivo.stem
        nombre = re.sub(r'\W+', '_', nombre)  # reemplaza espacios y caracteres especiales
        dfs[nombre] = pd.read_excel(archivo) # Store DataFrame in the dfs dictionary

    print("DataFrames creados:")
    for nombre_df in dfs.keys():
        print("-", nombre_df)

DataFrames creados:
- REPORTE_MCP_24022026_01
- RESUMEN_17062026_1
- RESUMEN_3
- RESUMEN_4_5_6
- RESUMEN_SEGUNDO_GRUPO
- RESUMEN_SEGUNDO_GRUPO_18062026_2
- RESUMEN_TAYACAJA
- RESUMEN_TERCER_GRUPO

In [10]:
import pandas as pd

for nombre, df in dfs.items():

    print("=" * 100)
    print(f"📄 DATAFRAME: {nombre}")
    print("=" * 100)

    # Shape
    print(f"\n📐 Shape: {df.shape[0]:,} filas × {df.shape[1]} columnas")

    # Memoria
    memoria = df.memory_usage(deep=True).sum() / 1024**2
    print(f"💾 Memoria: {memoria:.2f} MB")

    # Información general
    print("\n📋 Info:")
    df.info()

    # Columnas
    print("\n📝 Columnas:")
    for i, col in enumerate(df.columns, 1):
        print(f"{i:2d}. {col}")

    # Tipos de datos
    print("\n🔠 Tipos de datos:")
    print(df.dtypes)

    # Primeras filas
    print("\n👀 Primeras filas:")
    display(df.head())

    print("\n")

====================================================================================================
📄 DATAFRAME: REPORTE_MCP_24022026_01
====================================================================================================

📐 Shape: 3,432 filas × 7 columnas
💾 Memoria: 0.93 MB

📋 Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3432 entries, 0 to 3431
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   ITEM            3432 non-null   object
 1   COD_MCP_RENIEC  3431 non-null   float64
 2   DEPARTAMENTO    3431 non-null   object
 3   PROVINCIA       3431 non-null   object
 4   DISTRITO        3431 non-null   object
 5   MCP             3431 non-null   object
 6   CANTIDAD        3432 non-null   int64
dtypes: float64(1), int64(1), object(5)
memory usage: 187.8+ KB

📝 Columnas:
 1. ITEM
 2. COD_MCP_RENIEC
 3. DEPARTAMENTO
 4. PROVINCIA
 5. DISTRITO
 6. MCP
 7. CANTIDAD

🔠 Tipos de datos:
ITEM               object
COD_MCP_RENIEC    float64
DEPARTAMENTO       object
PROVINCIA          object
DISTRITO           object
MCP                object
CANTIDAD            int64
dtype: object

👀 Primeras filas:

,ITEM,COD_MCP_RENIEC,DEPARTAMENTO,PROVINCIA,DISTRITO,MCP,CANTIDAD
0,1,10106001.0,AMAZONAS,CHACHAPOYAS,CHUQUIBAMBA,LA MORADA,364
1,2,10201001.0,AMAZONAS,BAGUA,LA PECA,ARRAYAN,670
2,3,10201002.0,AMAZONAS,BAGUA,LA PECA,ESPITAL,134
3,4,10201003.0,AMAZONAS,BAGUA,LA PECA,PECA PALACIOS,74
4,5,10201004.0,AMAZONAS,BAGUA,LA PECA,SAN FRANCISCO,850

====================================================================================================
📄 DATAFRAME: RESUMEN_17062026_1
====================================================================================================

📐 Shape: 105 filas × 7 columnas
💾 Memoria: 0.03 MB

📋 Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 105 entries, 0 to 104
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   ITEM            105 non-null    object
 1   COD_MCP_RENIEC  104 non-null    float64
 2   DEPARTAMENTO    104 non-null    object
 3   PROVINCIA       104 non-null    object
 4   DISTRITO        104 non-null    object
 5   MCP             104 non-null    object
 6   CANTIDAD        105 non-null    int64
dtypes: float64(1), int64(1), object(5)
memory usage: 5.9+ KB

📝 Columnas:
 1. ITEM
 2. COD_MCP_RENIEC
 3. DEPARTAMENTO
 4. PROVINCIA
 5. DISTRITO
 6. MCP
 7. CANTIDAD

🔠 Tipos de datos:
ITEM               object
COD_MCP_RENIEC    float64
DEPARTAMENTO       object
PROVINCIA          object
DISTRITO           object
MCP                object
CANTIDAD            int64
dtype: object

👀 Primeras filas:

,ITEM,COD_MCP_RENIEC,DEPARTAMENTO,PROVINCIA,DISTRITO,MCP,CANTIDAD
0,1,50110100.0,AYACUCHO,HUAMANGA,TAMBILLO,MUYURINA,591
1,2,70801001.0,CUSCO,ESPINAR,ESPINAR,TINTAYA MARQUIRI,1362
2,3,70803001.0,CUSCO,ESPINAR,COPORAQUE,HUAYHUAHUASI,2425
3,4,70803002.0,CUSCO,ESPINAR,COPORAQUE,PUENTE CENTRAL APACHACO,4103
4,5,70803003.0,CUSCO,ESPINAR,COPORAQUE,TAHUAPALCCA,740

====================================================================================================
📄 DATAFRAME: RESUMEN_3
====================================================================================================

📐 Shape: 1,284 filas × 7 columnas
💾 Memoria: 0.35 MB

📋 Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1284 entries, 0 to 1283
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   ITEM            1284 non-null   object
 1   COD_MCP_RENIEC  1283 non-null   float64
 2   DEPARTAMENTO    1283 non-null   object
 3   PROVINCIA       1283 non-null   object
 4   DISTRITO        1283 non-null   object
 5   MCP             1283 non-null   object
 6   CANTIDAD        1284 non-null   int64
dtypes: float64(1), int64(1), object(5)
memory usage: 70.3+ KB

📝 Columnas:
 1. ITEM
 2. COD_MCP_RENIEC
 3. DEPARTAMENTO
 4. PROVINCIA
 5. DISTRITO
 6. MCP
 7. CANTIDAD

🔠 Tipos de datos:
ITEM               object
COD_MCP_RENIEC    float64
DEPARTAMENTO       object
PROVINCIA          object
DISTRITO           object
MCP                object
CANTIDAD            int64
dtype: object

👀 Primeras filas:

,ITEM,COD_MCP_RENIEC,DEPARTAMENTO,PROVINCIA,DISTRITO,MCP,CANTIDAD
0,1,10201001.0,AMAZONAS,BAGUA,LA PECA,ARRAYAN,678
1,2,10201004.0,AMAZONAS,BAGUA,LA PECA,SAN FRANCISCO,860
2,3,10201005.0,AMAZONAS,BAGUA,LA PECA,SAN ISIDRO,558
3,4,10201100.0,AMAZONAS,BAGUA,LA PECA,CHONZA ALTA,482
4,5,10202001.0,AMAZONAS,BAGUA,ARAMANGO,COPALLIN DE ARAMANGO,732

====================================================================================================
📄 DATAFRAME: RESUMEN_4_5_6
====================================================================================================

📐 Shape: 55 filas × 7 columnas
💾 Memoria: 0.02 MB

📋 Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 55 entries, 0 to 54
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   ITEM            55 non-null     object
 1   COD_MCP_RENIEC  54 non-null     float64
 2   DEPARTAMENTO    54 non-null     object
 3   PROVINCIA       54 non-null     object
 4   DISTRITO        54 non-null     object
 5   MCP             54 non-null     object
 6   CANTIDAD        55 non-null     int64
dtypes: float64(1), int64(1), object(5)
memory usage: 3.1+ KB

📝 Columnas:
 1. ITEM
 2. COD_MCP_RENIEC
 3. DEPARTAMENTO
 4. PROVINCIA
 5. DISTRITO
 6. MCP
 7. CANTIDAD

🔠 Tipos de datos:
ITEM               object
COD_MCP_RENIEC    float64
DEPARTAMENTO       object
PROVINCIA          object
DISTRITO           object
MCP                object
CANTIDAD            int64
dtype: object

👀 Primeras filas:

,ITEM,COD_MCP_RENIEC,DEPARTAMENTO,PROVINCIA,DISTRITO,MCP,CANTIDAD
0,1,10202001.0,AMAZONAS,BAGUA,ARAMANGO,COPALLIN DE ARAMANGO,663
1,2,10202002.0,AMAZONAS,BAGUA,ARAMANGO,EL MUYO,2524
2,3,10202003.0,AMAZONAS,BAGUA,ARAMANGO,EL PORVENIR,1177
3,4,10202004.0,AMAZONAS,BAGUA,ARAMANGO,LA LIBERTAD,489
4,5,10202005.0,AMAZONAS,BAGUA,ARAMANGO,NUMPARQUE,1299

====================================================================================================
📄 DATAFRAME: RESUMEN_SEGUNDO_GRUPO
====================================================================================================

📐 Shape: 41 filas × 7 columnas
💾 Memoria: 0.01 MB

📋 Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41 entries, 0 to 40
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   ITEM            41 non-null     object
 1   COD_MCP_RENIEC  40 non-null     float64
 2   DEPARTAMENTO    40 non-null     object
 3   PROVINCIA       40 non-null     object
 4   DISTRITO        40 non-null     object
 5   MCP             40 non-null     object
 6   CANTIDAD        41 non-null     int64
dtypes: float64(1), int64(1), object(5)
memory usage: 2.4+ KB

📝 Columnas:
 1. ITEM
 2. COD_MCP_RENIEC
 3. DEPARTAMENTO
 4. PROVINCIA
 5. DISTRITO
 6. MCP
 7. CANTIDAD

🔠 Tipos de datos:
ITEM               object
COD_MCP_RENIEC    float64
DEPARTAMENTO       object
PROVINCIA          object
DISTRITO           object
MCP                object
CANTIDAD            int64
dtype: object

👀 Primeras filas:

,ITEM,COD_MCP_RENIEC,DEPARTAMENTO,PROVINCIA,DISTRITO,MCP,CANTIDAD
0,1,10601001.0,AMAZONAS,CONDORCANQUI,NIEVA,CIRO ALEGRIA,2704
1,2,10601002.0,AMAZONAS,CONDORCANQUI,NIEVA,KIGKIS,3596
2,3,10601003.0,AMAZONAS,CONDORCANQUI,NIEVA,NUEVO SEASMI,2727
3,4,10601004.0,AMAZONAS,CONDORCANQUI,NIEVA,TAYUNTSA,1702
4,5,10601005.0,AMAZONAS,CONDORCANQUI,NIEVA,URAKUSA,2577

====================================================================================================
📄 DATAFRAME: RESUMEN_SEGUNDO_GRUPO_18062026_2
====================================================================================================

📐 Shape: 176 filas × 7 columnas
💾 Memoria: 0.05 MB

📋 Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 176 entries, 0 to 175
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   ITEM            176 non-null    object
 1   COD_MCP_RENIEC  175 non-null    float64
 2   DEPARTAMENTO    175 non-null    object
 3   PROVINCIA       175 non-null    object
 4   DISTRITO        175 non-null    object
 5   MCP             175 non-null    object
 6   CANTIDAD        176 non-null    int64
dtypes: float64(1), int64(1), object(5)
memory usage: 9.8+ KB

📝 Columnas:
 1. ITEM
 2. COD_MCP_RENIEC
 3. DEPARTAMENTO
 4. PROVINCIA
 5. DISTRITO
 6. MCP
 7. CANTIDAD

🔠 Tipos de datos:
ITEM               object
COD_MCP_RENIEC    float64
DEPARTAMENTO       object
PROVINCIA          object
DISTRITO           object
MCP                object
CANTIDAD            int64
dtype: object

👀 Primeras filas:

,ITEM,COD_MCP_RENIEC,DEPARTAMENTO,PROVINCIA,DISTRITO,MCP,CANTIDAD
0,1,10402001.0,AMAZONAS,LUYA,CAMPORREDONDO,COCOCHO,2589
1,2,10402002.0,AMAZONAS,LUYA,CAMPORREDONDO,GUADALUPE,931
2,3,20505001.0,ANCASH,CASMA,YAUTAN,CACHIPAMPA,2484
3,4,21206100.0,ANCASH,RECUAY,PARARIN,MARAVIA,254
4,5,21206101.0,ANCASH,RECUAY,PARARIN,SANTA ROSA DE RINCONADA,317

====================================================================================================
📄 DATAFRAME: RESUMEN_TAYACAJA
====================================================================================================

📐 Shape: 131 filas × 7 columnas
💾 Memoria: 0.04 MB

📋 Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 131 entries, 0 to 130
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   ITEM            131 non-null    object
 1   COD_MCP_RENIEC  130 non-null    float64
 2   DEPARTAMENTO    130 non-null    object
 3   PROVINCIA       130 non-null    object
 4   DISTRITO        130 non-null    object
 5   MCP             130 non-null    object
 6   COUNT(1)        131 non-null    int64
dtypes: float64(1), int64(1), object(5)
memory usage: 7.3+ KB

📝 Columnas:
 1. ITEM
 2. COD_MCP_RENIEC
 3. DEPARTAMENTO
 4. PROVINCIA
 5. DISTRITO
 6. MCP
 7. COUNT(1)

🔠 Tipos de datos:
ITEM               object
COD_MCP_RENIEC    float64
DEPARTAMENTO       object
PROVINCIA          object
DISTRITO           object
MCP                object
COUNT(1)            int64
dtype: object

👀 Primeras filas:

,ITEM,COD_MCP_RENIEC,DEPARTAMENTO,PROVINCIA,DISTRITO,MCP,COUNT(1)
0,1,80501001.0,HUANCAVELICA,TAYACAJA,PAMPAS,CASAY,336
1,2,80501002.0,HUANCAVELICA,TAYACAJA,PAMPAS,LLACTA CCOLLOY,209
2,3,80501003.0,HUANCAVELICA,TAYACAJA,PAMPAS,MANTACRA,342
3,4,80501004.0,HUANCAVELICA,TAYACAJA,PAMPAS,SAN JUAN DE MANTARO PACTI,497
4,5,80501005.0,HUANCAVELICA,TAYACAJA,PAMPAS,VIÑAS,362

====================================================================================================
📄 DATAFRAME: RESUMEN_TERCER_GRUPO
====================================================================================================

📐 Shape: 329 filas × 7 columnas
💾 Memoria: 0.09 MB

📋 Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 329 entries, 0 to 328
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   ITEM            329 non-null    object
 1   COD_MCP_RENIEC  328 non-null    float64
 2   DEPARTAMENTO    328 non-null    object
 3   PROVINCIA       328 non-null    object
 4   DISTRITO        328 non-null    object
 5   MCP             328 non-null    object
 6   CANTIDAD        329 non-null    int64
dtypes: float64(1), int64(1), object(5)
memory usage: 18.1+ KB

📝 Columnas:
 1. ITEM
 2. COD_MCP_RENIEC
 3. DEPARTAMENTO
 4. PROVINCIA
 5. DISTRITO
 6. MCP
 7. CANTIDAD

🔠 Tipos de datos:
ITEM               object
COD_MCP_RENIEC    float64
DEPARTAMENTO       object
PROVINCIA          object
DISTRITO           object
MCP                object
CANTIDAD            int64
dtype: object

👀 Primeras filas:

  ITEM  COD_MCP_RENIEC DEPARTAMENTO PROVINCIA DISTRITO       MCP  CANTIDAD
0    1      20101001.0       ANCASH    HUARAZ   HUARAZ   COYLLUR       816
1    2      20101002.0       ANCASH    HUARAZ   HUARAZ  HUALLCOR       359
2    3      20101003.0       ANCASH    HUARAZ   HUARAZ  HUAMARIN       692
3    4      20101004.0       ANCASH    HUARAZ   HUARAZ    ICHOCA       300
4    5      20101005.0       ANCASH    HUARAZ   HUARAZ     JAUNA       398

In [11]:
columna = "COD_MCP_RENIEC"

for nombre, df in dfs.items():

    print("="*100)
    print(f"📄 {nombre}")

    if columna not in df.columns:
        print(f"❌ La columna '{columna}' no existe.")
        continue

    s = df[columna]

    print(f"Tipo de dato      : {s.dtype}")
    print(f"Filas             : {len(s):,}")
    print(f"No nulos          : {s.notna().sum():,}")
    print(f"Nulos             : {s.isna().sum():,}")
    print(f"Valores únicos    : {s.nunique(dropna=True):,}")
    print(f"Duplicados        : {s.duplicated().sum():,}")

    print("\nPrimeros valores:")
    print(s.head(10).tolist())

    print("\n")

====================================================================================================
📄 REPORTE_MCP_24022026_01
Tipo de dato      : float64
Filas             : 3,432
No nulos          : 3,431
Nulos             : 1
Valores únicos    : 3,266
Duplicados        : 165

Primeros valores:
[10106001.0, 10201001.0, 10201002.0, 10201003.0, 10201004.0, 10201005.0, 10201006.0, 10202001.0, 10202002.0, 10202003.0]


====================================================================================================
📄 RESUMEN_17062026_1
Tipo de dato      : float64
Filas             : 105
No nulos          : 104
Nulos             : 1
Valores únicos    : 103
Duplicados        : 1

Primeros valores:
[50110100.0, 70801001.0, 70803001.0, 70803002.0, 70803003.0, 70803004.0, 80607001.0, 80607002.0, 80607003.0, 80607004.0]


====================================================================================================
📄 RESUMEN_3
Tipo de dato      : float64
Filas             : 1,284
No nulos          : 1,283
Nulos             : 1
Valores únicos    : 1,283
Duplicados        : 0

Primeros valores:
[10201001.0, 10201004.0, 10201005.0, 10201100.0, 10202001.0, 10202002.0, 10202003.0, 10202004.0, 10202005.0, 10202006.0]


====================================================================================================
📄 RESUMEN_4_5_6
Tipo de dato      : float64
Filas             : 55
No nulos          : 54
Nulos             : 1
Valores únicos    : 54
Duplicados        : 0

Primeros valores:
[10202001.0, 10202002.0, 10202003.0, 10202004.0, 10202005.0, 10202006.0, 10206001.0, 10206002.0, 10206100.0, 10206101.0]


====================================================================================================
📄 RESUMEN_SEGUNDO_GRUPO
Tipo de dato      : float64
Filas             : 41
No nulos          : 40
Nulos             : 1
Valores únicos    : 38
Duplicados        : 2

Primeros valores:
[10601001.0, 10601002.0, 10601003.0, 10601004.0, 10601005.0, 10601006.0, 10601100.0, 10603001.0, 10603002.0, 10603100.0]


====================================================================================================
📄 RESUMEN_SEGUNDO_GRUPO_18062026_2
Tipo de dato      : float64
Filas             : 176
No nulos          : 175
Nulos             : 1
Valores únicos    : 173
Duplicados        : 2

Primeros valores:
[10402001.0, 10402002.0, 20505001.0, 21206100.0, 21206101.0, 21210001.0, 21210002.0, 21210003.0, 21210100.0, 40106001.0]


====================================================================================================
📄 RESUMEN_TAYACAJA
Tipo de dato      : float64
Filas             : 131
No nulos          : 130
Nulos             : 1
Valores únicos    : 124
Duplicados        : 6

Primeros valores:
[80501001.0, 80501002.0, 80501003.0, 80501004.0, 80501005.0, 80501006.0, 80502001.0, 80502002.0, 80502003.0, 80503001.0]


====================================================================================================
📄 RESUMEN_TERCER_GRUPO
Tipo de dato      : float64
Filas             : 329
No nulos          : 328
Nulos             : 1
Valores únicos    : 287
Duplicados        : 41

Primeros valores:
[20101001.0, 20101002.0, 20101003.0, 20101004.0, 20101005.0, 20101006.0, 20101007.0, 20101008.0, 20101009.0, 20101010.0]

In [12]:
import pandas as pd

COLUMNA = "COD_MCP_RENIEC"

for nombre, df in dfs.items():

    if COLUMNA not in df.columns:
        print(f"⚠️ {nombre}: no existe la columna.")
        continue

    df[COLUMNA] = (
        df[COLUMNA]
        .apply(lambda x: pd.NA if pd.isna(x) else str(int(x)).zfill(9))
    )

print("✅ Limpieza finalizada.")

✅ Limpieza finalizada.

In [13]:
for nombre, df in dfs.items():

    print("="*90)
    print(nombre)

    s = df[COLUMNA]

    print("Tipo:", s.dtype)
    print("Primeros valores:")
    print(s.head(10).tolist())

    print("\nDistribución de longitudes:")
    print(s.dropna().str.len().value_counts().sort_index())

==========================================================================================
REPORTE_MCP_24022026_01
Tipo: object
Primeros valores:
['010106001', '010201001', '010201002', '010201003', '010201004', '010201005', '010201006', '010202001', '010202002', '010202003']

Distribución de longitudes:
COD_MCP_RENIEC
9    3431
Name: count, dtype: int64
==========================================================================================
RESUMEN_17062026_1
Tipo: object
Primeros valores:
['050110100', '070801001', '070803001', '070803002', '070803003', '070803004', '080607001', '080607002', '080607003', '080607004']

Distribución de longitudes:
COD_MCP_RENIEC
9    104
Name: count, dtype: int64
==========================================================================================
RESUMEN_3
Tipo: object
Primeros valores:
['010201001', '010201004', '010201005', '010201100', '010202001', '010202002', '010202003', '010202004', '010202005', '010202006']

Distribución de longitudes:
COD_MCP_RENIEC
9    1283
Name: count, dtype: int64
==========================================================================================
RESUMEN_4_5_6
Tipo: object
Primeros valores:
['010202001', '010202002', '010202003', '010202004', '010202005', '010202006', '010206001', '010206002', '010206100', '010206101']

Distribución de longitudes:
COD_MCP_RENIEC
9    54
Name: count, dtype: int64
==========================================================================================
RESUMEN_SEGUNDO_GRUPO
Tipo: object
Primeros valores:
['010601001', '010601002', '010601003', '010601004', '010601005', '010601006', '010601100', '010603001', '010603002', '010603100']

Distribución de longitudes:
COD_MCP_RENIEC
9    40
Name: count, dtype: int64
==========================================================================================
RESUMEN_SEGUNDO_GRUPO_18062026_2
Tipo: object
Primeros valores:
['010402001', '010402002', '020505001', '021206100', '021206101', '021210001', '021210002', '021210003', '021210100', '040106001']

Distribución de longitudes:
COD_MCP_RENIEC
9    175
Name: count, dtype: int64
==========================================================================================
RESUMEN_TAYACAJA
Tipo: object
Primeros valores:
['080501001', '080501002', '080501003', '080501004', '080501005', '080501006', '080502001', '080502002', '080502003', '080503001']

Distribución de longitudes:
COD_MCP_RENIEC
9    130
Name: count, dtype: int64
==========================================================================================
RESUMEN_TERCER_GRUPO
Tipo: object
Primeros valores:
['020101001', '020101002', '020101003', '020101004', '020101005', '020101006', '020101007', '020101008', '020101009', '020101010']

Distribución de longitudes:
COD_MCP_RENIEC
9    328
Name: count, dtype: int64

In [14]:
import pandas as pd
import numpy as np

#===========================================
# CONFIGURACIÓN
#===========================================

COLUMNAS = [
    "COD_MCP_RENIEC",
    "DEPARTAMENTO",
    "PROVINCIA",
    "DISTRITO",
    "MCP"
]

#===========================================
# LIMPIEZA GENERAL
#===========================================

def limpiar_texto(x):
    if pd.isna(x):
        return np.nan
    return (
        str(x)
        .strip()
        .upper()
    )

#===========================================
# CONSTRUIR HISTORIAL
#===========================================

lista = []
equivalencia_envios = []

for i, (nombre, df) in enumerate(dfs.items(), start=1):

    envio = f"{i:02d}"

    df = df.copy()

    # Normalizar textos
    for c in ["DEPARTAMENTO","PROVINCIA","DISTRITO","MCP"]:
        df[c] = df[c].apply(limpiar_texto)

    # Renombrar COUNT(1)
    if "COUNT(1)" in df.columns:
        df = df.rename(columns={"COUNT(1)":"CANTIDAD"})

    # Agregar identificadores
    df["ENVIO"] = envio
    df["ARCHIVO"] = nombre

    lista.append(df)

    equivalencia_envios.append({
        "ENVIO": envio,
        "ARCHIVO": nombre
    })

df_long = pd.concat(lista, ignore_index=True)

equivalencia_envios = pd.DataFrame(equivalencia_envios)

print(df_long.shape)
display(df_long.head())

display(equivalencia_envios)

(5553, 9)

,ITEM,COD_MCP_RENIEC,DEPARTAMENTO,PROVINCIA,DISTRITO,MCP,CANTIDAD,ENVIO,ARCHIVO
0,1,010106001,AMAZONAS,CHACHAPOYAS,CHUQUIBAMBA,LA MORADA,364,01,REPORTE_MCP_24022026_01
1,2,010201001,AMAZONAS,BAGUA,LA PECA,ARRAYAN,670,01,REPORTE_MCP_24022026_01
2,3,010201002,AMAZONAS,BAGUA,LA PECA,ESPITAL,134,01,REPORTE_MCP_24022026_01
3,4,010201003,AMAZONAS,BAGUA,LA PECA,PECA PALACIOS,74,01,REPORTE_MCP_24022026_01
4,5,010201004,AMAZONAS,BAGUA,LA PECA,SAN FRANCISCO,850,01,REPORTE_MCP_24022026_01

  ENVIO                           ARCHIVO
0    01           REPORTE_MCP_24022026_01
1    02                RESUMEN_17062026_1
2    03                         RESUMEN_3
3    04                     RESUMEN_4_5_6
4    05             RESUMEN_SEGUNDO_GRUPO
5    06  RESUMEN_SEGUNDO_GRUPO_18062026_2
6    07                  RESUMEN_TAYACAJA
7    08              RESUMEN_TERCER_GRUPO

In [15]:
revision = (
    df_long
    .groupby(["DEPARTAMENTO","MCP"])
    .agg(
        n_provincias=("PROVINCIA","nunique"),
        provincias=("PROVINCIA",
                    lambda x: " | ".join(sorted(set(x))))
    )
    .reset_index()
)

problemas = revision[revision["n_provincias"]>1]

display(problemas)

,DEPARTAMENTO,MCP,n_provincias,provincias
14,AMAZONAS,CUZUMATAC,2,BAGUA | CONDORCANQUI
18,AMAZONAS,EL PROGRESO,2,BONGARA | UTCUBAMBA
170,ANCASH,HUARIPAMPA,2,HUARAZ | HUARI
181,ANCASH,ICHOCA,2,HUARAZ | RECUAY
210,ANCASH,MESAPAMPA,2,BOLOGNESI | RECUAY
...,...,...,...,...
2979,PUNO,PARINA,2,LAMPA | PUNO
3020,PUNO,SAN ISIDRO,3,AZANGARO | EL COLLAO | SAN ANTONIO DE PUTINA
3043,PUNO,SANTA CRUZ,2,MELGAR | SANDIA
3245,SAN MARTIN,SANTA CRUZ,2,EL DORADO | TOCACHE
3247,SAN MARTIN,SANTA MARTHA,2,EL DORADO | SAN MARTIN

In [17]:
revision = (
    df_long
    .groupby(["DEPARTAMENTO","MCP"])
    .agg(
        provincias=("PROVINCIA",
                    lambda x: sorted(set(x))),
        distritos=("DISTRITO",
                    lambda x: sorted(set(x))),
        codigos=("COD_MCP_RENIEC",
                 lambda x: sorted(set(x.dropna())))
    )
    .reset_index()
)

revision["n_provincias"] = revision["provincias"].str.len()

problemas = revision.query("n_provincias > 1")

print(problemas)

     DEPARTAMENTO           MCP                                    provincias  \
14       AMAZONAS     CUZUMATAC                         [BAGUA, CONDORCANQUI]
18       AMAZONAS   EL PROGRESO                          [BONGARA, UTCUBAMBA]
170        ANCASH    HUARIPAMPA                               [HUARAZ, HUARI]
181        ANCASH        ICHOCA                              [HUARAZ, RECUAY]
210        ANCASH     MESAPAMPA                           [BOLOGNESI, RECUAY]
...           ...           ...                                           ...
2979         PUNO        PARINA                                 [LAMPA, PUNO]
3020         PUNO    SAN ISIDRO  [AZANGARO, EL COLLAO, SAN ANTONIO DE PUTINA]
3043         PUNO    SANTA CRUZ                              [MELGAR, SANDIA]
3245   SAN MARTIN    SANTA CRUZ                          [EL DORADO, TOCACHE]
3247   SAN MARTIN  SANTA MARTHA                       [EL DORADO, SAN MARTIN]

                                      distritos  \
14                               [IMAZA, NIEVA]
18                     [CAJARURO, YAMBRASBAMBA]
170                       [OLLEROS, SAN MARCOS]
181                             [HUARAZ, MARCA]
210        [CATAC, CHIQUIAN, RECUAY, TICAPAMPA]
...                                         ...
2979                        [CHUCUITO, OCUVIRI]
3020                 [ILAVE, PUTINA, SAN ANTON]
3043  [MACARI, PATAMBUCO, SANTA ROSA, UMACHIRI]
3245         [NUEVO PROGRESO, SAN JOSE DE SISA]
3247  [HUIMBAYOC, SAN JOSE DE SISA, SANTA ROSA]

                                codigos  n_provincias
14               [010206103, 010601006]             2
18               [010311002, 010702100]             2
170              [020108001, 020813004]             2
181              [020101004, 021204001]             2
210              [020301003, 021210001]             2
...                                 ...           ...
2979             [200106005, 200605100]             2
3020  [200213003, 201101001, 201201025]             3
3043             [200705003, 200806001]             2
3245             [210802003, 211001004]             2
3247  [210609003, 211001005, 211005100]             2

[73 rows x 6 columns]

In [18]:
revision_homonimos = (
    df_long
    .groupby(["ENVIO", "DEPARTAMENTO", "MCP"])
    .agg(
        n_provincias=("PROVINCIA", "nunique"),
        provincias=("PROVINCIA", lambda x: sorted(set(x))),
        n_codigos=("COD_MCP_RENIEC", "nunique"),
        codigos=("COD_MCP_RENIEC", lambda x: sorted(set(x))),
        n_distritos=("DISTRITO", "nunique"),
        distritos=("DISTRITO", lambda x: sorted(set(x)))
    )
    .reset_index()
)

homonimos = revision_homonimos.query("n_provincias > 1")

print(f"Casos encontrados: {len(homonimos)}")

display(homonimos)

Casos encontrados: 80

,ENVIO,DEPARTAMENTO,MCP,n_provincias,provincias,n_codigos,codigos,n_distritos,distritos
13,01,AMAZONAS,CUZUMATAC,2,"[BAGUA, CONDORCANQUI]",2,"[010206103, 010601006]",2,"[IMAZA, NIEVA]"
164,01,ANCASH,HUARIPAMPA,2,"[HUARAZ, HUARI]",2,"[020108001, 020813004]",2,"[OLLEROS, SAN MARCOS]"
175,01,ANCASH,ICHOCA,2,"[HUARAZ, RECUAY]",2,"[020101004, 021204001]",2,"[HUARAZ, MARCA]"
203,01,ANCASH,MESAPAMPA,2,"[BOLOGNESI, RECUAY]",2,"[020301003, 021210001]",4,"[CATAC, CHIQUIAN, RECUAY, TICAPAMPA]"
212,01,ANCASH,PACCHA,2,"[HUARAZ, PALLASCA]",2,"[020102010, 021008001]",2,"[INDEPENDENCIA, PALLASCA]"
...,...,...,...,...,...,...,...,...,...
4056,03,LA LIBERTAD,BARRO NEGRO,2,"[JULCAN, OTUZCO]",2,"[120411001, 121003100]",2,"[CALAMARCA, USQUIL]"
4106,03,LA LIBERTAD,VICTOR RAUL HAYA DE LA TORRE,2,"[TRUJILLO, VIRU]",2,"[120102004, 121201007]",2,"[HUANCHACO, VIRU]"
4320,03,PUNO,CANGALLI,2,"[AZANGARO, EL COLLAO]",2,"[200213001, 201201003]",2,"[ILAVE, SAN ANTON]"
4428,03,PUNO,SAN ISIDRO,2,"[AZANGARO, EL COLLAO]",2,"[200213003, 201201025]",2,"[ILAVE, SAN ANTON]"
5080,08,CAJAMARCA,LA COLPA,2,"[CHOTA, HUALGAYOC]",2,"[060619007, 060701007]",2,"[BAMBAMARCA, CHALAMARCA]"

In [19]:
revision_cod = (
    df_long
    .groupby("COD_MCP_RENIEC")
    .agg(
        n_mcp=("MCP","nunique"),
        mcps=("MCP", lambda x: sorted(set(x))),
        n_provincias=("PROVINCIA","nunique"),
        provincias=("PROVINCIA", lambda x: sorted(set(x)))
    )
    .reset_index()
)

revision_cod = revision_cod.query("n_mcp > 1")

print(len(revision_cod))

display(revision_cod)

29

,COD_MCP_RENIEC,n_mcp,mcps,n_provincias,provincias
52,010701005,2,"[MAÃ‘UMAL, MAÑUMAL]",1,[UTCUBAMBA]
56,010701009,2,"[Ã‘UNYA JALCA, ÑUNYA JALCA]",1,[UTCUBAMBA]
474,030504005,2,"[SANTIAGO DE QQUEUÃ‘APAMPA, SANTIAGO DE QQUEUÑ...",1,[COTABAMBAS]
494,030506104,2,"[YANAWARA QUEUÃ‘A, YANAWARA QUEUÑA]",1,[COTABAMBAS]
673,050308004,2,"[COMPAÃ‘IA BAJA, COMPAÑIA BAJA]",1,[HUANTA]
930,060307003,2,"[JORGE CHÁVEZ, JORGE CHÃ_X0081_VEZ]",1,[CELENDIN]
956,060408100,2,"[TOLON, TOLÓN]",1,[CONTUMAZA]
1053,060609900,2,"[MARCOPAMPA - EL ARENAL, MARCOPAMPA EL ARENAL]",1,[CHOTA]
1079,060615900,2,"[PUÃ‘A, PUÑA]",1,[CHOTA]
1581,080202005,2,"[SAN PEDRO DE Ã‘AHUINCUCHO, SAN PEDRO DE ÑAHUI...",1,[ACOBAMBA]
1592,080205701,2,"[CUÃ‘I, CUÑI]",1,[ACOBAMBA]
1674,080501005,2,"[VIÃ‘AS, VIÑAS]",1,[TAYACAJA]
1730,080517006,2,"[QUISPIÃ‘ICAS, QUISPIÑICAS]",1,[TAYACAJA]
1958,090204002,2,"[SAN ANTONIO DE Ã‘AUZA, SAN ANTONIO DE ÑAUZA]",1,[AMBO]
2493,130117100,2,"[LA CRIA Y PAMPA LA VICTORIA, VILLA LA CRIA - ...",1,[CHICLAYO]
2501,130203001,2,"[CHIÃ‘AMA, CHIÑAMA]",1,[FERREÑAFE]
2530,130308010,2,"[Ã‘AUPE EL TELEGRAFO, ÑAUPE EL TELEGRAFO]",1,[LAMBAYEQUE]
2751,180305003,2,"[SAN MIGUEL DE ENEÃ‘AS, SAN MIGUEL DE ENEÑAS]",1,[OXAPAMPA]
2884,200102016,2,"[MARCA ESQUEÃ‘A, MARCA ESQUEÑA]",1,[PUNO]
2903,200104004,2,"[ISAÃ‘URA, ISAÑURA]",1,[PUNO]
2943,200204005,2,"[MARIANO CHANCATUMA DE Ã‘AUPAPAMPA, MARIANO CH...",1,[AZANGARO]
2961,200213004,2,"[VILLA HERMOSA CAÃ‘ICUTO, VILLA HERMOSA CAÑICUTO]",1,[AZANGARO]
3032,200410010,2,"[PAVITA CENTRAL, SAN ANTONIO DE PAVITA]",1,[CHUCUITO]
3182,201201022,2,"[OCOÃ‘A, OCOÑA]",1,[EL COLLAO]
3200,201201704,2,"[UNIÃ“N DE SANTA CRUZ DE QUIMSA CHATA, UNIÓN D...",1,[EL COLLAO]
3208,201202008,2,"[VILLA ASUNCIÃ“N ACCASO, VILLA ASUNCIÓN ACCASO]",1,[EL COLLAO]
3353,211004101,2,"[NUEVO PACAIPAMPA, PACAIPAMPA]",1,[EL DORADO]
3358,220108001,2,"[ALTO PERÃŠ - ANCOMARCA, ALTO PERÚ - ANCOMARCA]",1,[TACNA]
3361,220201001,2,"[MAURE KALLACHIRI, MAURE KALLAPUMA]",1,[TARATA]

In [20]:
revision_cod2 = (
    df_long
    .groupby(["DEPARTAMENTO","PROVINCIA","MCP"])
    .agg(
        n_codigos=("COD_MCP_RENIEC","nunique"),
        codigos=("COD_MCP_RENIEC",
                 lambda x: sorted(set(x)))
    )
    .reset_index()
)

revision_cod2 = revision_cod2.query("n_codigos > 1")

print(len(revision_cod2))

display(revision_cod2)

35

,DEPARTAMENTO,PROVINCIA,MCP,n_codigos,codigos
9,AMAZONAS,BAGUA,ESPITAL,2,"[010201002, 010205100]"
17,AMAZONAS,BAGUA,PECA PALACIOS,2,"[010201003, 010205101]"
20,AMAZONAS,BAGUA,TOMAQUE,2,"[010201006, 010205102]"
62,AMAZONAS,UTCUBAMBA,MIRAFLORES,2,"[010701007, 010703100]"
477,APURIMAC,CHINCHEROS,MIRAFLORES,2,"[030705004, 030709101]"
524,APURIMAC,COTABAMBAS,PAMPURA,2,"[030501004, 030505101]"
651,AYACUCHO,HUANTA,CARHUAHURAN,2,"[050301001, 050311300]"
654,AYACUCHO,HUANTA,CCANO,2,"[050301002, 050311100]"
678,AYACUCHO,HUANTA,IQUICHA,2,"[050301004, 050311102]"
694,AYACUCHO,HUANTA,PAMPALCA,2,"[050301006, 050311103]"
823,AYACUCHO,VICTOR FAJARDO,UMASI,2,"[050704003, 050708100]"
914,CAJAMARCA,CELENDIN,EL TINGO,2,"[060304002, 060309005]"
968,CAJAMARCA,CHOTA,EL NARANJO,3,"[060614100, 060615003, 060619003]"
981,CAJAMARCA,CHOTA,LA PALMA,2,"[060605002, 060615005]"
1145,CAJAMARCA,JAEN,TABACAL,2,"[060801009, 060804002]"
1167,CAJAMARCA,SAN IGNACIO,LA LIMA,2,"[061103004, 061105004]"
1365,CUSCO,LA CONVENCION,MANITEA ALTA,2,"[070909004, 070918901]"
1368,CUSCO,LA CONVENCION,MIARIA,2,"[070902005, 070915903]"
1372,CUSCO,LA CONVENCION,NUEVA LUZ,2,"[070902006, 070915901]"
1373,CUSCO,LA CONVENCION,NUEVO MUNDO,2,"[070902007, 070915902]"
1378,CUSCO,LA CONVENCION,PALESTINA,2,"[070909005, 070917100]"
1505,HUANCAVELICA,ACOBAMBA,VISTA ALEGRE,2,"[080202009, 080203004]"
1682,HUANCAVELICA,HUANCAVELICA,SAN MARTIN,2,"[080102004, 080105002]"
1733,HUANCAVELICA,TAYACAJA,COCHABAMBA CHICO,2,"[080511001, 080533100]"
1764,HUANCAVELICA,TAYACAJA,MATARA,2,"[080523007, 080533102]"
1820,HUANCAVELICA,TAYACAJA,SOCOS,2,"[080523006, 080533103]"
1835,HUANCAVELICA,TAYACAJA,VIRGEN DEL CARMEN DE HUAYLACUCHO,2,"[080511004, 080533101]"
1952,HUANUCO,HUAMALIES,SAN CRISTOBAL,2,"[090401008, 090407011]"
2032,HUANUCO,HUANUCO,SANTA ISABEL,2,"[090108012, 090113008]"
2117,HUANUCO,PUERTO INCA,LOS ANGELES,2,"[090802100, 090804002]"
2623,MADRE DE DIOS,TAMBOPATA,ALEGRIA,2,"[160101001, 160103100]"
2652,MOQUEGUA,MARISCAL NIETO,TITIRE,2,"[170102100, 170104003]"
2937,PUNO,CHUCUITO,MOLINO,2,"[200401005, 200410009]"
3255,SAN MARTIN,EL DORADO,SANTA MARTHA,2,"[211001005, 211005100]"
3293,SAN MARTIN,MOYOBAMBA,CARRIZAL,2,"[210101701, 210104001]"

In [21]:
revision_cod = (
    df_long
    .groupby("COD_MCP_RENIEC")
    .agg(
        DEPARTAMENTO=("DEPARTAMENTO", lambda x: sorted(set(x))),
        PROVINCIA=("PROVINCIA", lambda x: sorted(set(x))),
        MCP=("MCP", lambda x: sorted(set(x))),
        DISTRITO=("DISTRITO", lambda x: sorted(set(x))),
        ENVIOS=("ENVIO", lambda x: sorted(set(x)))
    )
    .reset_index()
)

revision_cod["n_mcp"] = revision_cod["MCP"].str.len()

revision_cod = revision_cod.query("n_mcp > 1")

display(revision_cod)

,COD_MCP_RENIEC,DEPARTAMENTO,PROVINCIA,MCP,DISTRITO,ENVIOS,n_mcp
52,010701005,[AMAZONAS],[UTCUBAMBA],"[MAÃ‘UMAL, MAÑUMAL]",[BAGUA GRANDE],"[01, 03]",2
56,010701009,[AMAZONAS],[UTCUBAMBA],"[Ã‘UNYA JALCA, ÑUNYA JALCA]",[BAGUA GRANDE],"[01, 03]",2
474,030504005,[APURIMAC],[COTABAMBAS],"[SANTIAGO DE QQUEUÃ‘APAMPA, SANTIAGO DE QQUEUÑ...",[HAQUIRA],"[01, 03]",2
494,030506104,[APURIMAC],[COTABAMBAS],"[YANAWARA QUEUÃ‘A, YANAWARA QUEUÑA]",[CHALLHUAHUACHO],"[01, 03]",2
673,050308004,[AYACUCHO],[HUANTA],"[COMPAÃ‘IA BAJA, COMPAÑIA BAJA]",[SIVIA],"[01, 03, 08]",2
930,060307003,[CAJAMARCA],[CELENDIN],"[JORGE CHÁVEZ, JORGE CHÃ_X0081_VEZ]",[MIGUEL IGLESIAS],"[01, 03]",2
956,060408100,[CAJAMARCA],[CONTUMAZA],"[TOLON, TOLÓN]",[YONAN],"[03, 08]",2
1053,060609900,[CAJAMARCA],[CHOTA],"[MARCOPAMPA - EL ARENAL, MARCOPAMPA EL ARENAL]",[LAJAS],"[03, 08]",2
1079,060615900,[CAJAMARCA],[CHOTA],"[PUÃ‘A, PUÑA]",[TACABAMBA],"[03, 08]",2
1581,080202005,[HUANCAVELICA],[ACOBAMBA],"[SAN PEDRO DE Ã‘AHUINCUCHO, SAN PEDRO DE ÑAHUI...",[ANTA],"[01, 03]",2
1592,080205701,[HUANCAVELICA],[ACOBAMBA],"[CUÃ‘I, CUÑI]",[MARCAS],"[01, 03]",2
1674,080501005,[HUANCAVELICA],[TAYACAJA],"[VIÃ‘AS, VIÑAS]",[PAMPAS],"[01, 03, 07]",2
1730,080517006,[HUANCAVELICA],[TAYACAJA],"[QUISPIÃ‘ICAS, QUISPIÑICAS]",[PAZOS],"[01, 03, 07]",2
1958,090204002,[HUANUCO],[AMBO],"[SAN ANTONIO DE Ã‘AUZA, SAN ANTONIO DE ÑAUZA]",[CONCHAMARCA],"[01, 03]",2
2493,130117100,[LAMBAYEQUE],[CHICLAYO],"[LA CRIA Y PAMPA LA VICTORIA, VILLA LA CRIA - ...",[PATAPO],"[01, 03, 04]",2
2501,130203001,[LAMBAYEQUE],[FERREÑAFE],"[CHIÃ‘AMA, CHIÑAMA]",[CAÑARIS],"[01, 03, 04]",2
2530,130308010,[LAMBAYEQUE],[LAMBAYEQUE],"[Ã‘AUPE EL TELEGRAFO, ÑAUPE EL TELEGRAFO]",[OLMOS],"[01, 03]",2
2751,180305003,[PASCO],[OXAPAMPA],"[SAN MIGUEL DE ENEÃ‘AS, SAN MIGUEL DE ENEÑAS]",[VILLA RICA],"[01, 03]",2
2884,200102016,[PUNO],[PUNO],"[MARCA ESQUEÃ‘A, MARCA ESQUEÑA]",[ACORA],"[01, 03]",2
2903,200104004,[PUNO],[PUNO],"[ISAÃ‘URA, ISAÑURA]",[CAPACHICA],"[01, 03]",2
2943,200204005,[PUNO],[AZANGARO],"[MARIANO CHANCATUMA DE Ã‘AUPAPAMPA, MARIANO CH...",[ASILLO],"[01, 03]",2
2961,200213004,[PUNO],[AZANGARO],"[VILLA HERMOSA CAÃ‘ICUTO, VILLA HERMOSA CAÑICUTO]",[SAN ANTON],"[01, 03]",2
3032,200410010,[PUNO],[CHUCUITO],"[PAVITA CENTRAL, SAN ANTONIO DE PAVITA]",[ZEPITA],"[01, 03, 08]",2
3182,201201022,[PUNO],[EL COLLAO],"[OCOÃ‘A, OCOÑA]",[ILAVE],"[01, 03, 08]",2
3200,201201704,[PUNO],[EL COLLAO],"[UNIÃ“N DE SANTA CRUZ DE QUIMSA CHATA, UNIÓN D...",[ILAVE],"[01, 03, 08]",2
3208,201202008,[PUNO],[EL COLLAO],"[VILLA ASUNCIÃ“N ACCASO, VILLA ASUNCIÓN ACCASO]",[PILCUYO],"[01, 03]",2
3353,211004101,[SAN MARTIN],[EL DORADO],"[NUEVO PACAIPAMPA, PACAIPAMPA]",[SAN MARTIN],"[03, 05]",2
3358,220108001,[TACNA],[TACNA],"[ALTO PERÃŠ - ANCOMARCA, ALTO PERÚ - ANCOMARCA]",[PALCA],"[01, 03]",2
3361,220201001,[TACNA],[TARATA],"[MAURE KALLACHIRI, MAURE KALLAPUMA]",[TARATA],"[01, 03, 08]",2

In [22]:
revision_mcp = (
    df_long
    .groupby(["DEPARTAMENTO","PROVINCIA","MCP"])
    .agg(
        CODIGOS=("COD_MCP_RENIEC", lambda x: sorted(set(x))),
        DISTRITOS=("DISTRITO", lambda x: sorted(set(x))),
        ENVIOS=("ENVIO", lambda x: sorted(set(x)))
    )
    .reset_index()
)

revision_mcp["n_codigos"] = revision_mcp["CODIGOS"].str.len()

revision_mcp = revision_mcp.query("n_codigos > 1")

display(revision_mcp)

,DEPARTAMENTO,PROVINCIA,MCP,CODIGOS,DISTRITOS,ENVIOS,n_codigos
9,AMAZONAS,BAGUA,ESPITAL,"[010201002, 010205100]","[BAGUA, LA PECA]","[01, 03]",2
17,AMAZONAS,BAGUA,PECA PALACIOS,"[010201003, 010205101]","[BAGUA, LA PECA]","[01, 03]",2
20,AMAZONAS,BAGUA,TOMAQUE,"[010201006, 010205102]","[BAGUA, LA PECA]","[01, 03]",2
62,AMAZONAS,UTCUBAMBA,MIRAFLORES,"[010701007, 010703100]","[BAGUA GRANDE, CUMBA]","[01, 03]",2
477,APURIMAC,CHINCHEROS,MIRAFLORES,"[030705004, 030709101]","[ANCO HUALLO, ROCCHACC]",[01],2
524,APURIMAC,COTABAMBAS,PAMPURA,"[030501004, 030505101]","[MARA, TAMBOBAMBA]","[01, 03, 04]",2
651,AYACUCHO,HUANTA,CARHUAHURAN,"[050301001, 050311300]","[HUANTA, UCHURACCAY]","[01, 03, 04, 08]",2
654,AYACUCHO,HUANTA,CCANO,"[050301002, 050311100]","[HUANTA, UCHURACCAY]","[01, 08]",2
678,AYACUCHO,HUANTA,IQUICHA,"[050301004, 050311102]","[HUANTA, UCHURACCAY]","[01, 08]",2
694,AYACUCHO,HUANTA,PAMPALCA,"[050301006, 050311103]","[HUANTA, UCHURACCAY]","[01, 08]",2
823,AYACUCHO,VICTOR FAJARDO,UMASI,"[050704003, 050708100]","[CANARIA, HUALLA]",[01],2
914,CAJAMARCA,CELENDIN,EL TINGO,"[060304002, 060309005]","[HUASMIN, SOROCHUCO]","[01, 03]",2
968,CAJAMARCA,CHOTA,EL NARANJO,"[060614100, 060615003, 060619003]","[CHALAMARCA, QUEROCOTO, TACABAMBA]","[01, 03, 08]",3
981,CAJAMARCA,CHOTA,LA PALMA,"[060605002, 060615005]","[CHADIN, TACABAMBA]","[01, 03, 08]",2
1145,CAJAMARCA,JAEN,TABACAL,"[060801009, 060804002]","[CHONTALI, JAEN]","[01, 03]",2
1167,CAJAMARCA,SAN IGNACIO,LA LIMA,"[061103004, 061105004]","[HUARANGO, LA COIPA]",[01],2
1365,CUSCO,LA CONVENCION,MANITEA ALTA,"[070909004, 070918901]","[KIMBIRI, MANITEA]","[01, 03]",2
1368,CUSCO,LA CONVENCION,MIARIA,"[070902005, 070915903]","[ECHARATE, MEGANTONI]","[01, 03]",2
1372,CUSCO,LA CONVENCION,NUEVA LUZ,"[070902006, 070915901]","[ECHARATE, MEGANTONI]","[01, 03]",2
1373,CUSCO,LA CONVENCION,NUEVO MUNDO,"[070902007, 070915902]","[ECHARATE, MEGANTONI]","[01, 03]",2
1378,CUSCO,LA CONVENCION,PALESTINA,"[070909005, 070917100]","[CIELO PUNCO, KIMBIRI]","[01, 03]",2
1505,HUANCAVELICA,ACOBAMBA,VISTA ALEGRE,"[080202009, 080203004]","[ANDABAMBA, ANTA, PAUCARA]","[01, 03]",2
1682,HUANCAVELICA,HUANCAVELICA,SAN MARTIN,"[080102004, 080105002]","[ACOBAMBILLA, CUENCA]",[01],2
1733,HUANCAVELICA,TAYACAJA,COCHABAMBA CHICO,"[080511001, 080533100]","[HUACHOCOLPA, LAMBRAS]","[01, 03, 07]",2
1764,HUANCAVELICA,TAYACAJA,MATARA,"[080523007, 080533102]","[LAMBRAS, SURCUBAMBA]","[01, 03, 07]",2
1820,HUANCAVELICA,TAYACAJA,SOCOS,"[080523006, 080533103]","[LAMBRAS, SURCUBAMBA]","[01, 03, 07]",2
1835,HUANCAVELICA,TAYACAJA,VIRGEN DEL CARMEN DE HUAYLACUCHO,"[080511004, 080533101]","[HUACHOCOLPA, LAMBRAS]","[01, 03, 07]",2
1952,HUANUCO,HUAMALIES,SAN CRISTOBAL,"[090401008, 090407011]","[LLATA, MONZON]","[01, 06]",2
2032,HUANUCO,HUANUCO,SANTA ISABEL,"[090108012, 090113008]","[SAN PABLO DE PILLAO, SANTA MARIA DEL VALLE]","[01, 03]",2
2117,HUANUCO,PUERTO INCA,LOS ANGELES,"[090802100, 090804002]","[PUERTO INCA, TOURNAVISTA]","[01, 03]",2
2623,MADRE DE DIOS,TAMBOPATA,ALEGRIA,"[160101001, 160103100]","[LAS PIEDRAS, TAMBOPATA]","[01, 02, 05, 08]",2
2652,MOQUEGUA,MARISCAL NIETO,TITIRE,"[170102100, 170104003]","[CARUMAS, SAN CRISTOBAL]","[01, 03]",2
2937,PUNO,CHUCUITO,MOLINO,"[200401005, 200410009]","[DESAGUADERO, JULI, ZEPITA]","[01, 03]",2
3255,SAN MARTIN,EL DORADO,SANTA MARTHA,"[211001005, 211005100]","[SAN JOSE DE SISA, SANTA ROSA]","[01, 03]",2
3293,SAN MARTIN,MOYOBAMBA,CARRIZAL,"[210101701, 210104001]","[JEPELACIO, MOYOBAMBA]","[01, 03, 08]",2

In [25]:
import pandas as pd
import numpy as np

#=========================================================
# 1. RENOMBRAR CANTIDAD
#=========================================================

df_long = df_long.copy()

if "COUNT(1)" in df_long.columns:
    df_long = df_long.rename(columns={"COUNT(1)": "CANTIDAD"})


#=========================================================
# 2. TABLA BASE
#=========================================================

base = (
    df_long[
        [
            "DEPARTAMENTO",
            "PROVINCIA",
            "MCP"
        ]
    ]
    .drop_duplicates()
    .reset_index(drop=True)
)


#=========================================================
# 3. AGREGAR COLUMNAS DE CADA ENVÍO
#=========================================================

df_consolidado = base.copy()

envios = sorted(df_long["ENVIO"].unique())

for envio in envios:

    aux = (
        df_long[df_long["ENVIO"] == envio]
        [
            [
                "DEPARTAMENTO",
                "PROVINCIA",
                "MCP",
                "COD_MCP_RENIEC",
                "DISTRITO",
                "CANTIDAD"
            ]
        ]
        .rename(columns={
            "COD_MCP_RENIEC": f"COD_{envio}",
            "DISTRITO": f"DIST_{envio}",
            "CANTIDAD": f"CANT_{envio}"
        })
    )

    df_consolidado = df_consolidado.merge(
        aux,
        how="left",
        on=["DEPARTAMENTO","PROVINCIA","MCP"]
    )


#=========================================================
# 4. COLUMNAS AUXILIARES
#=========================================================

cod_cols  = sorted([c for c in df_consolidado.columns if c.startswith("COD_")])
dist_cols = sorted([c for c in df_consolidado.columns if c.startswith("DIST_")])


# Último código conocido
df_consolidado["COD_ACTUAL"] = (
    df_consolidado[cod_cols]
    .ffill(axis=1)
    .iloc[:, -1]
)

# Último distrito conocido
df_consolidado["DIST_ACTUAL"] = (
    df_consolidado[dist_cols]
    .ffill(axis=1)
    .iloc[:, -1]
)

# Número de envíos
df_consolidado["N_ENVIOS"] = (
    df_consolidado[cod_cols]
    .notna()
    .sum(axis=1)
)

# Cambio de código
df_consolidado["CAMBIO_CODIGO"] = (
    df_consolidado[cod_cols]
    .nunique(axis=1, dropna=True)
)

# Cambio de distrito
df_consolidado["CAMBIO_DISTRITO"] = (
    df_consolidado[dist_cols]
    .nunique(axis=1, dropna=True)
)

/tmp/ipykernel_1845/1795503221.py:85: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  .ffill(axis=1)

In [26]:
#=========================================================
# 5. ¿EL NOMBRE APARECE EN OTRAS PROVINCIAS?
#=========================================================

homonimos = (
    df_long
    .groupby(["DEPARTAMENTO","MCP"])
    .agg(
        N_PROVINCIAS=("PROVINCIA","nunique"),
        PROVINCIAS=("PROVINCIA",
                    lambda x: " | ".join(sorted(set(x))))
    )
    .reset_index()
)

df_consolidado = df_consolidado.merge(
    homonimos,
    on=["DEPARTAMENTO","MCP"],
    how="left"
)


#=========================================================
# 6. ¿ESTA MCP TUVO MÁS DE UN CÓDIGO?
#=========================================================

revision_codigos = (
    df_long
    .groupby(["DEPARTAMENTO","PROVINCIA","MCP"])
    .agg(
        N_CODIGOS=("COD_MCP_RENIEC","nunique"),
        CODIGOS=("COD_MCP_RENIEC",
                 lambda x: " | ".join(sorted(set(x.dropna()))))
    )
    .reset_index()
)

df_consolidado = df_consolidado.merge(
    revision_codigos,
    on=["DEPARTAMENTO","PROVINCIA","MCP"],
    how="left"
)

In [27]:
def clasificar(row):

    if row["N_PROVINCIAS"] > 1:
        return "HOMONIMO"

    if row["N_CODIGOS"] > 1:
        return "CAMBIO_CODIGO"

    if row["CAMBIO_DISTRITO"] > 1:
        return "CAMBIO_DISTRITO"

    return "OK"


df_consolidado["OBSERVACION"] = (
    df_consolidado
    .apply(clasificar, axis=1)
)

In [28]:
df_consolidado

,DEPARTAMENTO,PROVINCIA,MCP,COD_01,DIST_01,CANT_01,COD_02,DIST_02,CANT_02,COD_03,...,COD_ACTUAL,DIST_ACTUAL,N_ENVIOS,CAMBIO_CODIGO,CAMBIO_DISTRITO,N_PROVINCIAS,PROVINCIAS,N_CODIGOS,CODIGOS,OBSERVACION
0,AMAZONAS,CHACHAPOYAS,LA MORADA,010106001,CHUQUIBAMBA,364.0,NaN,NaN,NaN,NaN,...,010106001,CHUQUIBAMBA,1,1,1,1.0,CHACHAPOYAS,1.0,010106001,OK
1,AMAZONAS,BAGUA,ARRAYAN,010201001,LA PECA,670.0,NaN,NaN,NaN,010201001,...,010201001,LA PECA,2,1,1,1.0,BAGUA,1.0,010201001,OK
2,AMAZONAS,BAGUA,ESPITAL,010201002,LA PECA,134.0,NaN,NaN,NaN,010205100,...,010205100,BAGUA,2,2,2,1.0,BAGUA,2.0,010201002 | 010205100,CAMBIO_CODIGO
3,AMAZONAS,BAGUA,PECA PALACIOS,010201003,LA PECA,74.0,NaN,NaN,NaN,010205101,...,010205101,BAGUA,2,2,2,1.0,BAGUA,2.0,010201003 | 010205101,CAMBIO_CODIGO
4,AMAZONAS,BAGUA,SAN FRANCISCO,010201004,LA PECA,850.0,NaN,NaN,NaN,010201004,...,010201004,LA PECA,2,1,1,1.0,BAGUA,1.0,010201004,OK
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3840,PUNO,HUANCANE,JASANA POCSELLIN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,200508100,TARACO,1,1,1,1.0,HUANCANE,1.0,200508100,OK
3841,SAN MARTIN,SAN MARTIN,LECHE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,210609100,HUIMBAYOC,1,1,1,1.0,SAN MARTIN,1.0,210609100,OK
3842,SAN MARTIN,SAN MARTIN,BELLO HORIZONTE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,210621100,LA BANDA DE SHILCAYO,1,1,1,1.0,SAN MARTIN,1.0,210621100,OK
3843,SAN MARTIN,PICOTA,PARAISO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,210909100,TRES UNIDOS,1,1,1,1.0,PICOTA,1.0,210909100,OK
3844,TACNA,TARATA,MAURE KALLAPUMA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,220201001,TARATA,1,1,1,1.0,TARATA,1.0,220201001,OK

In [29]:
#=========================================================
# CLASIFICACIÓN DE OBSERVACIONES
#=========================================================

def observaciones(row):

    obs = []

    # El nombre aparece en más de una provincia
    if row["N_PROVINCIAS"] > 1:
        obs.append("HOMONIMO")

    # La misma MCP tuvo más de un código
    if row["N_CODIGOS"] > 1:
        obs.append("CAMBIO_CODIGO")

    # La misma MCP cambió de distrito
    if row["CAMBIO_DISTRITO"] > 1:
        obs.append("CAMBIO_DISTRITO")

    if len(obs) == 0:
        return "OK"

    return " | ".join(obs)


df_consolidado["OBSERVACIONES"] = (
    df_consolidado
    .apply(observaciones, axis=1)
)

df_consolidado["REQUIERE_REVISION"] = (
    df_consolidado["OBSERVACIONES"] != "OK"
)

In [30]:
print("Resumen de incidencias\n")

print(df_consolidado["OBSERVACIONES"].value_counts())

print("\n")

print(
    f"MCP que requieren revisión: "
    f"{df_consolidado['REQUIERE_REVISION'].sum():,}"
)

Resumen de incidencias

OBSERVACIONES
OK                                            3309
CAMBIO_DISTRITO                                270
HOMONIMO                                       152
CAMBIO_CODIGO | CAMBIO_DISTRITO                 50
CAMBIO_CODIGO                                   32
HOMONIMO | CAMBIO_CODIGO | CAMBIO_DISTRITO      16
HOMONIMO | CAMBIO_DISTRITO                      12
HOMONIMO | CAMBIO_CODIGO                         4
Name: count, dtype: int64


MCP que requieren revisión: 536

In [31]:
df_revision = (
    df_consolidado
    .query("REQUIERE_REVISION")
    .sort_values(
        [
            "OBSERVACIONES",
            "DEPARTAMENTO",
            "PROVINCIA",
            "MCP"
        ]
    )
)

display(df_revision.head())

,DEPARTAMENTO,PROVINCIA,MCP,COD_01,DIST_01,CANT_01,COD_02,DIST_02,CANT_02,COD_03,...,N_ENVIOS,CAMBIO_CODIGO,CAMBIO_DISTRITO,N_PROVINCIAS,PROVINCIAS,N_CODIGOS,CODIGOS,OBSERVACION,OBSERVACIONES,REQUIERE_REVISION
47,AMAZONAS,UTCUBAMBA,MIRAFLORES,010701007,BAGUA GRANDE,2333.0,NaN,NaN,NaN,010701007,...,2,1,1,1.0,UTCUBAMBA,2.0,010701007 | 010703100,CAMBIO_CODIGO,CAMBIO_CODIGO,True
526,APURIMAC,CHINCHEROS,MIRAFLORES,030705004,ANCO HUALLO,690.0,NaN,NaN,NaN,NaN,...,1,1,1,1.0,CHINCHEROS,2.0,030705004 | 030709101,CAMBIO_CODIGO,CAMBIO_CODIGO,True
527,APURIMAC,CHINCHEROS,MIRAFLORES,030709101,ROCCHACC,157.0,NaN,NaN,NaN,NaN,...,1,1,1,1.0,CHINCHEROS,2.0,030705004 | 030709101,CAMBIO_CODIGO,CAMBIO_CODIGO,True
646,AYACUCHO,HUANTA,CARHUAHURAN,050301001,HUANTA,55.0,NaN,NaN,NaN,050301001,...,4,2,1,1.0,HUANTA,2.0,050301001 | 050311300,CAMBIO_CODIGO,CAMBIO_CODIGO,True
649,AYACUCHO,HUANTA,CCANO,050301002,HUANTA,22.0,NaN,NaN,NaN,NaN,...,2,2,1,1.0,HUANTA,2.0,050301002 | 050311100,CAMBIO_CODIGO,CAMBIO_CODIGO,True

In [33]:
df_consolidado

,DEPARTAMENTO,PROVINCIA,MCP,COD_01,DIST_01,CANT_01,COD_02,DIST_02,CANT_02,COD_03,...,N_ENVIOS,CAMBIO_CODIGO,CAMBIO_DISTRITO,N_PROVINCIAS,PROVINCIAS,N_CODIGOS,CODIGOS,OBSERVACION,OBSERVACIONES,REQUIERE_REVISION
0,AMAZONAS,CHACHAPOYAS,LA MORADA,010106001,CHUQUIBAMBA,364.0,NaN,NaN,NaN,NaN,...,1,1,1,1.0,CHACHAPOYAS,1.0,010106001,OK,OK,False
1,AMAZONAS,BAGUA,ARRAYAN,010201001,LA PECA,670.0,NaN,NaN,NaN,010201001,...,2,1,1,1.0,BAGUA,1.0,010201001,OK,OK,False
2,AMAZONAS,BAGUA,ESPITAL,010201002,LA PECA,134.0,NaN,NaN,NaN,010205100,...,2,2,2,1.0,BAGUA,2.0,010201002 | 010205100,CAMBIO_CODIGO,CAMBIO_CODIGO | CAMBIO_DISTRITO,True
3,AMAZONAS,BAGUA,PECA PALACIOS,010201003,LA PECA,74.0,NaN,NaN,NaN,010205101,...,2,2,2,1.0,BAGUA,2.0,010201003 | 010205101,CAMBIO_CODIGO,CAMBIO_CODIGO | CAMBIO_DISTRITO,True
4,AMAZONAS,BAGUA,SAN FRANCISCO,010201004,LA PECA,850.0,NaN,NaN,NaN,010201004,...,2,1,1,1.0,BAGUA,1.0,010201004,OK,OK,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3840,PUNO,HUANCANE,JASANA POCSELLIN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1,1,1,1.0,HUANCANE,1.0,200508100,OK,OK,False
3841,SAN MARTIN,SAN MARTIN,LECHE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1,1,1,1.0,SAN MARTIN,1.0,210609100,OK,OK,False
3842,SAN MARTIN,SAN MARTIN,BELLO HORIZONTE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1,1,1,1.0,SAN MARTIN,1.0,210621100,OK,OK,False
3843,SAN MARTIN,PICOTA,PARAISO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1,1,1,1.0,PICOTA,1.0,210909100,OK,OK,False
3844,TACNA,TARATA,MAURE KALLAPUMA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1,1,1,1.0,TARATA,1.0,220201001,OK,OK,False